### ISSUE TITLE
Review parsing assumptions to avoid panics

### ISSUE THREAD

**Issue by lilopkins** [lilopkins/metar-rs#5]
Thanks for the quick fix but another METAR from my database for a few days later (2018-06-21) also had a missing character which caused a panic. I'd suggest a more widespread review of the assumptions made during parsing so errors are picked up more systematically.

The second problem METAR is:

EGPC 211650Z 33026G37KT 9999 FEW021 12/7 Q1026

with a missing leading digit on the dew point (should be 12/07, presumably).

_Originally posted by @ed-davies in https://github.com/lilopkins/metar-rs/issues/3#issuecomment-562259102_

**Comment by lilopkins** [comment]
A panic was raised from the METAR:
```
ESSA 081950Z 22021KT 9999 OVC025 06/03 Q0973 R01L/29//95 R08/29//95 R01R/29//95 NOSIG
```

**Comment by lilopkins** [comment]
Commit 2b014c3781687b347b4e35cdd0d1e42ddf03b87e should fix this - data assumptions were reviewed and now almost empty METARs parse successfully.

**Comment by ed-davies** [comment]
The EGPC METAR in the first post of this issue still causes a panic with version 0.4.0.

I'm pretty sure 0.4.0 incorporates the 2b014c3 commit - at least, the version of lib.rs in my .cargo/…/src directory has the modified line 209 as shown in the commit.

**Comment by lilopkins** [comment]
I have had another look and this was the only assumption I hadn't gone through and checked. As a precaution I have also added some more thorough tests with some data close to correct but malformed. Hopefully this will fix the panics.

**Comment by ed-davies** [comment]
Yep, 0.4.1 fixes the problem. Thanks for this.
